apiVersion: v1
kind: Service
metadata:
  name: frontend-deployment-service
  namespace: dev
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30500 # Specify the nodePort (a port in the range 30000-32767)
  type: LoadBalancer
