# trigger:
#   branches:
#     include:
#       - develop

#  Use pipeline run button (manual UI or API)
pr: none
trigger: none  #  Explicitly disables automatic CI triggers

variables:
- group: ovh-secrets
- name: imageName
  value: dtma/frontend
- name: imageTag
  value: $(Build.BuildId)

steps:
# 1. Download the Kubeconfig File from Azure DevOps Secure Files
- task: DownloadSecureFile@1
  displayName: 'GetKubeconfig'
  name: GetKubeconfig
  inputs:
    secureFile: 'kubeconfig-dtma.yml'  # Use the name of your Kubeconfig secure file in Azure DevOps
  
#2. Authenticating Kubernetes.'
- script: |
      echo "Authenticating Kubernetes"
      mkdir -p ~/.kube
      cp $KUBECONFIG_FILE ~/.kube/config 
      kubectl config use-context kubernetes-admin@DTMA
      kubectl config get-contexts

  env:
    KUBECONFIG_FILE: $(GetKubeconfig.secureFilePath)
  displayName: 'Authenticating Kubernetes'

# 3. Deploying Image to OVH
- task: Kubernetes@1
  displayName: 'Deploy to OVH Kubernetes Cluster'
  inputs:
    connectionType: 'Kubernetes service connection'
    kubernetesServiceEndpoint: 'Kubernetes-dtma'  # Use your secure file path or environment variable
    command: 'apply'
    arguments: '-k **/K8s/overlays/staging'
    # Optional: Add namespace if needed (default or specify another)
    namespace: 'test'
